version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_SERVER=${MSSQL_SERVER}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
    volumes:
      - ./public:/app/public:rw
      - ./data:/app/data:rw
      - node_modules:/app/node_modules
      - ./.next:/app/.next:rw
    restart: unless-stopped
    # Debug için komut satırı çıktılarını daha detaylı göster
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    user: "root"
    command: >
      sh -c "
        chmod -R 777 /app/public &&
        chmod -R 777 /app/data &&
        chmod -R 777 /app/.next &&
        node server.js
      "

volumes:
  node_modules: 