version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_SERVER=${MSSQL_SERVER}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
    volumes:
      - app_data:/app/data
      - app_dishes:/app/public/dishes
      - app_categories:/app/public/categories
    restart: unless-stopped
    # Debug için komut satırı çıktılarını daha detaylı göster
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  app_data:
  app_dishes:
  app_categories: 